### ISSUE TITLE
Реализованы не все требования ДЗ

### ISSUE THREAD

**Issue by coursar** [daniil-jd/HomeWorkItPark2#24]
Читайте внимательнее

**Comment by daniil-jd** [comment]
а вот тут не понял( 
в дз 8 пунктов, выполнил все 
что конкретно не так?

**Comment by coursar** [comment]
Выгрузка в CSV всего каталога - зачем выгружать отдельную запись?

**Comment by daniil-jd** [comment]
добавил выгрузку всего каталога
она доступна на странице каталога после добавления хотя бы одного авто

**Comment by coursar** [comment]
В большинстве случаев клиент не допрёт )) и лучше делать выгрузку пустого файла с заголовками, который будет "шаблоном для заполнения". Тогда вам не придётся объяснять, в каком формате нужно заполнять и с какими полями.
