### ISSUE TITLE
Плохая идея

### ISSUE THREAD

**Issue by coursar** [daniil-jd/HomeWorkItPark2#25]
https://github.com/daniil-jd/HomeWorkItPark2/blob/0c7d14e16fff2d01ae29b004aae5340926920329/src/main/java/ru/home/service/FileService.java#L19

Уж лучше тогда используйте Files, который умеет создавать временные директории

**Comment by daniil-jd** [comment]
я понял, в чем было дело
забыл, где нужно задавать переменные (на локальной машине)
поправил
