### ISSUE TITLE
Зачем создавать дубликаты файлов, если можно просто отдавать один и тот же файл?

### ISSUE THREAD

**Issue by coursar** [daniil-jd/HomeWorkItPark2#28]
https://github.com/daniil-jd/HomeWorkItPark2/blob/0c7d14e16fff2d01ae29b004aae5340926920329/src/main/java/ru/home/service/FileService.java#L78-L84

**Comment by daniil-jd** [comment]
Изначально изображение хранится в статике. Если загружен файл из csv и для него нет изображения, то ему ставится дефолтное изображение из статика. При загрузке первого файла без картинки, происходит копирование дефолтного изображения из статика в папку аплоад, только один раз.  В таком случае работа с авто из csv и созданными вручную одинаковая - поиск изображений происходит в одной папке.

**Comment by coursar** [comment]
Это понятно, но если ваша csv будет состоять из пары тысяч записей, сколько раз вы скопируете картинку-заглушку?

**Comment by daniil-jd** [comment]
Скопирую один раз - в случае, если она еще не скопирована, в самый первый раз.

**Comment by coursar** [comment]
Один раз на каждую запись или всего один раз?

**Comment by daniil-jd** [comment]
Всего один раз. Как только в первый раз найдется авто без сохраненного фото, файл будет скопирован. Далее для других авто без фото копирование не производится.
