### ISSUE TITLE
Single Responsibility

### ISSUE THREAD

**Issue by coursar** [daniil-jd/HomeWorkItPark2#29]
https://github.com/daniil-jd/HomeWorkItPark2/blob/0c7d14e16fff2d01ae29b004aae5340926920329/src/main/java/ru/home/service/FileService.java#L17-L103

Этот сервис должен отвечать либо за работу с CSV, либо за работу с файлами

**Comment by daniil-jd** [comment]
разделил на FileService и CsvService
