### ISSUE TITLE
Поправить оформление

### ISSUE THREAD

**Issue by coursar** [daniil-jd/HomeWorkItPark2#36]
![Screenshot from 2019-05-08 18-50-50](https://user-images.githubusercontent.com/3601892/57389465-ee78d080-71c2-11e9-8747-1202b3cf1f71.png)

По бокам должны быть отступы, текст не должен прилипать к границе

![Screenshot from 2019-05-08 18-56-26](https://user-images.githubusercontent.com/3601892/57389521-08b2ae80-71c3-11e9-9e1e-7abeaefe6d12.png)

Кнопки должны быть выровнены и хотя бы в едином стиле

**Comment by daniil-jd** [comment]
поправил
